-- This group used to set its module priority on install and record a per-module
-- version. Neither exists in a single package: load order now comes from where
-- these items sit in the tree, and the version is the package's own.
