#!/usr/bin/env python3
"""
check_valid_callsites.py -- fail if a trigger calls an svo.valid function that
does not exist.

Almost every trigger and alias in svof is one line calling into `svo.valid`:

    svo.valid.tree_cured_paralysis()

`svo.valid` is a plain table created by `Setup.lua:130` as `svo.valid or {}`,
with no `__index`, so a name nothing defines reads as nil and the call raises
"attempt to call a nil value". Mudlet sends that to the error console and moves
on, so the line the trigger was watching for simply stops being acted on. The
affliction is not added, or not removed, or not diagnosed, and the only trace
is in a tab nobody has open.

Most of the names are not written anywhere as literals. They are generated by
loops over affliction lists:

    for _,j in ipairs(afflist) do valid['simple' .. j] = function () ... end end

so a name is defined if and only if it appears in the right list. That makes
the two files agree by accident rather than by construction, and when they stop
agreeing nothing says so. Both halves of it happen: a trigger can be added for
an affliction that never gets into the list, and a name can be dropped from a
list that still has triggers pointing at it.

This resolves every generator loop to the set of names it produces, then checks
every `svo.valid.<name>()` call in src/triggers and src/aliases against it.

The loop forms in use, all of which have to be handled, because missing one
under-reports and an under-reporting gate is worse than none:

    for _, aff in ipairs{'a', 'b'}          -- no parentheses
    for _, aff in pairs({ herb = {...} })   -- names are in the VALUES
    for i = 1, #listvar do local aff = listvar[i]
    valid['proper_'..status..name]          -- two variables

Pre-existing unresolved names live in known_unresolved_valid.json, the way
check_renamed_callsites.py records its own. Every one of them is absent from
the 2018 module xmls too, so none is conversion damage. Recording them means
the count can only go down: a new one fails immediately, and fixing an old one
fails until it is removed from the record.

    python tools/check_valid_callsites.py
    python tools/check_valid_callsites.py --write-known
"""
import argparse
import io
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "src")
KNOWN = os.path.join(HERE, "known_unresolved_valid.json")

# Where the generator loops live. Every dynamic svo.valid name comes from one
# of these three.
GENERATORS = [
    ("svo (trigger functions)", "Main_trigger_functions.lua"),
    ("svo (trigger functions)", "Simple_aff_trigger_functions.lua"),
    ("svo (trigger functions)", "Diag_trigger_functions.lua"),
]

# Written out by hand rather than generated, so no loop produces them.
HANDWRITTEN_DYNAMIC = {"tree_cured_": {"burn", "burns"}}

# Below these, the reading is broken rather than the source clean.
CALL_FLOOR = 500

# Per-prefix floors, because a single total is not a floor at all. The first
# version summed literals and generated names and failed below 200, which 351
# literals cleared on their own - so breaking the generic_cures_data
# declaration, losing 111 generated names outright, was a clean pass.
#
# Well below today's counts, so a real edit passes and a loop that has stopped
# being readable does not.
GENERATOR_FLOORS = {
    "simple": 100,
    "diag_": 100,
    "generic_": 80,
    "tree_cured_": 60,
    "herb_cured_": 40,
    "salve_cured_": 10,
    "focus_cured_": 12,
    "smoke_cured_": 8,
}


def read(path):
    """Source with line endings normalised, so a Windows checkout and the Linux
    runner read the same text."""
    with io.open(path, "rb") as fh:
        return fh.read().replace(b"\r\n", b"\n").decode("utf-8", "replace")


def lua_files(root):
    for d, _, fs in os.walk(root):
        if "3rdparty" in d:
            continue
        for f in fs:
            if f.endswith(".lua"):
                yield os.path.join(d, f)


def table_body(src, open_idx):
    depth = 0
    for k in range(open_idx, len(src)):
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                return src[open_idx:k + 1]
    return src[open_idx:]


def loop_names(src, idx, back=9000):
    """Names from the nearest enclosing loop above `idx`.

    Tries the innermost loop first and falls outward, because the herb, smoke
    and salve maps nest one loop inside another and the names live in the
    outer table's VALUES, not in the inner loop's own variable.
    """
    base = max(0, idx - back)
    seg = src[base:idx]
    cands = []
    for m in re.finditer(
            r"for\s[^\n]*?\b(?:ipairs|pairs)\s*\(?\s*(\{|[A-Za-z_][\w.]*)", seg):
        cands.append((m.start(), m.group(1), base + m.start(1)))
    for m in re.finditer(r"for\s+\w+\s*=\s*\d+\s*,\s*#(\w+)", seg):
        cands.append((m.start(), m.group(1), None))

    for _, what, at in sorted(cands, reverse=True):
        if what == "{":
            names = set(re.findall(r"'(\w+)'", table_body(src, at)))
            if names:
                return names
        else:
            decl = list(re.finditer(r"\b%s\s*=\s*\{" % re.escape(what), seg))
            if decl:
                start = src.index("{", base + decl[-1].end() - 1)
                names = set(re.findall(r"'(\w+)'", table_body(src, start)))
                if names:
                    return names
    return set()


def collect_definitions():
    """(literal names, {prefix: names}, {suffix: names}, two-part prefixes)."""
    literal = set()
    prefixed = defaultdict(set)
    suffixed = defaultdict(set)
    twopart = defaultdict(set)

    for root in ("scripts", "triggers", "aliases"):
        base = os.path.join(SRC, root)
        if not os.path.isdir(base):
            continue
        for p in lua_files(base):
            s = read(p)
            literal |= set(re.findall(r"(?:svo\.)?valid\.([A-Za-z_]\w*)\s*=", s))
            literal |= set(re.findall(
                r"(?:svo\.)?valid\[['\"]([^'\"]+)['\"]\]\s*=", s))
            literal |= set(re.findall(
                r"function\s+(?:svo\.)?valid\.([A-Za-z_]\w*)", s))

    for parts in GENERATORS:
        src = read(os.path.join(SRC, "scripts", *parts))
        for m in re.finditer(r"valid\[\s*'([a-z_]+)'\s*\.\.\s*\w+\s*\]\s*=", src):
            prefixed[m.group(1)] |= loop_names(src, m.start())
        for m in re.finditer(r"valid\[\s*(\w+)\s*\.\.\s*'(\w+)'\s*\]\s*=", src):
            suffixed[m.group(2)] |= loop_names(src, m.start())
        for m in re.finditer(
                r"valid\[\s*'([a-z_]+)'\s*\.\.\s*\w+\s*\.\.\s*\w+\s*\]\s*=", src):
            twopart[m.group(1)] |= loop_names(src, m.start())

    for pfx, names in HANDWRITTEN_DYNAMIC.items():
        prefixed[pfx] |= names

    return literal, dict(prefixed), dict(suffixed), dict(twopart)


def resolver(literal, prefixed, suffixed, twopart):
    def resolves(name):
        if name in literal:
            return True
        for pfx, names in prefixed.items():
            if name.startswith(pfx) and name[len(pfx):] in names:
                return True
        for suf, names in suffixed.items():
            if name.endswith(suf) and name[:-len(suf)] in names:
                return True
        # proper_<status><bodypart>: both halves come from the same loop table
        for pfx, names in twopart.items():
            if not name.startswith(pfx):
                continue
            rest = name[len(pfx):]
            for a in names:
                if rest.startswith(a) and rest[len(a):]:
                    return True
        return False
    return resolves


def collect_calls():
    calls = defaultdict(list)
    for root in ("triggers", "aliases"):
        base = os.path.join(SRC, root)
        if not os.path.isdir(base):
            continue
        for p in lua_files(base):
            rel = os.path.relpath(p, REPO).replace(os.sep, "/")
            for m in re.finditer(r"(?:svo\.)?\bvalid\.([A-Za-z_]\w*)\s*\(",
                                 read(p)):
                calls[m.group(1)].append(rel)
    return calls


def load_known():
    if not os.path.exists(KNOWN):
        return set()
    with io.open(KNOWN, encoding="utf-8") as fh:
        return {(e["file"], e["name"]) for e in json.load(fh)["known"]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-known", action="store_true",
                    help="record the current unresolved calls and exit")
    a = ap.parse_args()

    literal, prefixed, suffixed, twopart = collect_definitions()
    resolves = resolver(literal, prefixed, suffixed, twopart)
    calls = collect_calls()

    generated = sum(len(v) for v in prefixed.values())

    problems = []
    if len(calls) < CALL_FLOOR:
        problems.append("found only %d distinct svo.valid calls, expected at "
                        "least %d - this check is reading less than it should"
                        % (len(calls), CALL_FLOOR))
    for pfx, floor in sorted(GENERATOR_FLOORS.items()):
        got = len(prefixed.get(pfx, ()))
        if got < floor:
            problems.append("the %r loop produced only %d names, expected at "
                            "least %d - it has stopped being readable, and "
                            "every call it should define now looks dead"
                            % (pfx, got, floor))

    unresolved = []
    for name in sorted(calls):
        if resolves(name):
            continue
        for f in sorted(set(calls[name])):
            unresolved.append({"file": f, "name": name})

    if a.write_known:
        if problems:
            print("refusing to record while the reading looks broken - "
                  "%s NOT written:" % KNOWN)
            for p in problems:
                print("  [FAIL] " + p)
            return 1
        payload = {
            "note": "svo.valid calls in src/triggers and src/aliases that "
                    "resolve to nothing. Every one is absent from the 2018 "
                    "module xmls too, so none is conversion damage. Recorded "
                    "so the count can only go down: a new one fails, and "
                    "fixing one of these fails until it is removed from here.",
            "known": sorted(unresolved, key=lambda e: (e["name"], e["file"])),
        }
        with io.open(KNOWN, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(payload, fh, indent=2)
            fh.write("\n")
        print("wrote %s: %d pre-existing unresolved call(s)"
              % (KNOWN, len(unresolved)))
        return 0

    known = load_known()
    new = [e for e in unresolved if (e["file"], e["name"]) not in known]
    fixed = known - {(e["file"], e["name"]) for e in unresolved}

    print("%d distinct svo.valid names called from src/triggers and "
          "src/aliases" % len(calls))
    print("  %d defined as literals, %d generated by %d loops"
          % (len(literal), generated, len(prefixed) + len(suffixed) + len(twopart)))
    print()

    for e in new:
        print("[FAIL] svo.valid.%s() has no definition anywhere" % e["name"])
        print("           called from %s" % e["file"])
    for f, n in sorted(fixed):
        print("[FAIL] svo.valid.%s() now resolves, and %s still records it as "
              "unresolved" % (n, os.path.basename(KNOWN)))
        print("           remove that entry in the same commit that fixed it")
    for p in problems:
        print("[FAIL] " + p)

    bad = len(new) + len(fixed) + len(problems)
    if bad:
        print("\nsvo.valid is a plain table with no __index, so a name nothing "
              "defines\nraises into the error console and the trigger's line "
              "stops being acted on.")
        print("If a call is deliberately dead, record it with --write-known.")
        print("\nVALID CALL SITES FAILED - %d problem(s)" % bad)
        return 1

    print("every svo.valid call resolves (%d known pre-existing dead call(s) "
          "ignored)" % len(known))
    return 0


if __name__ == "__main__":
    sys.exit(main())
