#!/usr/bin/env python3
"""
check_valid_callsites.py -- fail if a trigger calls an svo.valid function that
does not exist.

Almost every trigger and alias in svof is one line calling into `svo.valid`:

    svo.valid.tree_cured_paralysis()

`svo.valid` is a plain table created by `Setup.lua:130` as `svo.valid or {}`,
with no `__index`, so a name nothing defines reads as nil and the call raises
"attempt to call a nil value". Mudlet sends that to the error console and moves
on, so the line the trigger was watching for simply stops being acted on. The
affliction is not added, or not removed, or not diagnosed, and the only trace
is in a tab nobody has open.

Most of the names are not written anywhere as literals. They are generated by
loops over affliction lists:

    for _, aff in pairs(herb) do valid['herb_cured_'..aff] = function() ... end end

so a name is defined if and only if it appears in the right list. That makes
the two files agree by accident rather than by construction, and when they stop
agreeing nothing says so. Both halves of it happen: a trigger can be added for
an affliction that never gets into the list, and a name can be dropped from a
list that still has triggers pointing at it.

The simple family no longer works that way. It is generated from svo.dict - one
handler per entry with an `aff` block - so its names cannot drift from the
dictionary, and resolving a simple call means reading the dictionary rather
than a list. dict_simple_names() below does that.

This resolves every generator loop to the set of names it produces, then checks
every `svo.valid.<name>()` call in src/triggers and src/aliases against it.

The loop forms in use, all of which have to be handled, because missing one
under-reports and an under-reporting gate is worse than none:

    for _, aff in ipairs{'a', 'b'}          -- no parentheses
    for _, aff in pairs({ herb = {...} })   -- names are in the VALUES
    for i = 1, #listvar do local aff = listvar[i]
    valid['proper_'..status..name]          -- two variables

Pre-existing unresolved names live in known_unresolved_valid.json, the way
check_renamed_callsites.py records its own. Every one of them is absent from
the 2018 module xmls too, so none is conversion damage. Recording them means
the count can only go down: a new one fails immediately, and fixing an old one
fails until it is removed from the record.

    python tools/check_valid_callsites.py
    python tools/check_valid_callsites.py --write-known
"""
import argparse
import io
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "src")
KNOWN = os.path.join(HERE, "known_unresolved_valid.json")

sys.path.insert(0, HERE)
# The simple family is derived from the dictionary now rather than listed, so
# resolving it means reading the dictionary. Imported rather than
# re-implemented: check_derived_lists walks the literal by brace depth instead
# of matching it, because a string or a comment holding a brace moves a regex's
# idea of where an entry ends, and two gates disagreeing about what the
# dictionary says is worse than either being wrong alone.
from check_derived_lists import entries as _dict_entries  # noqa: E402
from check_derived_lists import read as _read_script      # noqa: E402

# Where the generator loops live. Every dynamic svo.valid name comes from one
# of these three.
GENERATORS = [
    ("svo (trigger functions)", "Main_trigger_functions.lua"),
    ("svo (trigger functions)", "Simple_aff_trigger_functions.lua"),
    ("svo (trigger functions)", "Diag_trigger_functions.lua"),
]

# Written out by hand rather than generated, so no loop produces them.
#
# svo.dict.cantmorph is created after the dictionary literal, under
# `if svo.haveskillset('metamorphosis')`, so the literal walk below does not
# see it and the simple family would look one name short. Nothing in
# src/triggers calls simplecantmorph - Setup.lua builds that trigger at
# runtime - so leaving it out would not produce a false pass either way, but
# an under-read set is still an under-read set.
HANDWRITTEN_DYNAMIC = {"simple": {"cantmorph"}}

# Below these, the reading is broken rather than the source clean.
CALL_FLOOR = 500

# Per-prefix floors, because a single total is not a floor at all. The first
# version summed literals and generated names and failed below 200, which 351
# literals cleared on their own - so breaking the generic_cures_data
# declaration, losing 111 generated names outright, was a clean pass.
#
# Well below today's counts, so a real edit passes and a loop that has stopped
# being readable does not.
# diag_, generic_ and tree_cured_ are deliberately absent: those families were
# inverted into svo.valid.diag / .generic / .tree_cured, which take the name as
# an argument, so there is no generated per-name family left to floor. What
# guards them now is check_name_arguments() below, which reads the name each
# call passes, and NAME_CALL_FLOOR under it.
#
# simple stays, and its floor now guards the dictionary read rather than a
# literal: if the brace walk or the no_simple_handler read comes back empty,
# this family collapses to the four names the fracture loop still generates and
# every other simple call site reads as dead.
GENERATOR_FLOORS = {
    "simple": 100,
    "herb_cured_": 40,
    "salve_cured_": 10,
    "focus_cured_": 12,
    "smoke_cured_": 8,
}

# The handlers that take an affliction name as their first argument, and what
# each one needs that name to be - the same test the handler itself makes at
# runtime, so a call that passes here does not errorf there:
#
#   diag           an entry with an `aff` block (diagnose_end indexes .aff), or
#                  godfeelings, which diagnose_end special-cases
#   generic        an entry that is not a defence. Judged by the def flag, not
#                  by an `aff` block: healmana has no `aff` block and is a real
#                  caller, and insomnia is a defence that keeps one.
#   tree_cured     an entry, or one of TREE_SPECIAL in Main_trigger_functions
#   generic_cure,  an entry with a `gone` block, which both index
#   generic_cured
#
# Before this, the gate saw only that `generic` was defined and never read
# its argument, so d2160f6's generic('burn') (no such entry) and
# generic('insomnia') (a defence) both passed.
NAME_FAMILIES = ("diag", "generic", "tree_cured", "generic_cure", "generic_cured")

# Created after the dictionary literal, so the literal walk does not see them.
RUNTIME_ENTRIES = {"cantmorph": {"aff"}}

# Below this, the call-site reading is broken rather than the source clean.
NAME_CALL_FLOOR = 250


def read(path):
    """Source with line endings normalised, so a Windows checkout and the Linux
    runner read the same text."""
    with io.open(path, "rb") as fh:
        return fh.read().replace(b"\r\n", b"\n").decode("utf-8", "replace")


def lua_files(root):
    for d, _, fs in os.walk(root):
        if "3rdparty" in d:
            continue
        for f in fs:
            if f.endswith(".lua"):
                yield os.path.join(d, f)


def table_body(src, open_idx):
    depth = 0
    for k in range(open_idx, len(src)):
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                return src[open_idx:k + 1]
    return src[open_idx:]


def loop_names(src, idx, back=9000):
    """Names from the nearest enclosing loop above `idx`.

    Tries the innermost loop first and falls outward, because the herb, smoke
    and salve maps nest one loop inside another and the names live in the
    outer table's VALUES, not in the inner loop's own variable.
    """
    base = max(0, idx - back)
    seg = src[base:idx]
    cands = []
    for m in re.finditer(
            r"for\s[^\n]*?\b(?:ipairs|pairs)\s*\(?\s*(\{|[A-Za-z_][\w.]*)", seg):
        cands.append((m.start(), m.group(1), base + m.start(1)))
    for m in re.finditer(r"for\s+\w+\s*=\s*\d+\s*,\s*#(\w+)", seg):
        cands.append((m.start(), m.group(1), None))

    for _, what, at in sorted(cands, reverse=True):
        if what == "{":
            names = set(re.findall(r"'(\w+)'", table_body(src, at)))
            if names:
                return names
        else:
            decl = list(re.finditer(r"\b%s\s*=\s*\{" % re.escape(what), seg))
            if decl:
                start = src.index("{", base + decl[-1].end() - 1)
                names = set(re.findall(r"'(\w+)'", table_body(src, start)))
                if names:
                    return names
    return set()


def dict_simple_names():
    """The affliction names the simple family generates a handler for.

    Two facts, read from the two places that state them. Every dictionary entry
    with an `aff` block gets one, which is the same predicate svo.vaff uses to
    decide a name is an affliction it can add. The anti-illusion probes are
    excluded, because their aff.oncompleted takes the real affliction's name
    and checkslows and checkwrithes index svo.affsp with it, so a bare call
    raises - Simple_aff_trigger_functions.lua names them in
    `no_simple_handler`, and that table is read here rather than repeated.

    Both reads fail loudly rather than quietly. A dictionary read that comes
    back empty drops this family below its floor in GENERATOR_FLOORS. An
    exclusion read that comes back empty goes the other way - it makes
    simplecheckwrithes resolve, and known_unresolved_valid.json records that
    call as dead, so the gate fails on a name that started resolving.
    """
    bals, _ = _dict_entries(_read_script(
        "svo (actions dictionary)", "Dictionary_of_actions_(affs-defs-misc).lua"))
    simple = _read_script("svo (trigger functions)",
                          "Simple_aff_trigger_functions.lua")
    m = re.search(r"local no_simple_handler = \{(.*?)\n  \}", simple, re.S)
    excluded = set(re.findall(r"(\w+)\s*=\s*true", m.group(1))) if m else set()
    return {n for n, b in bals.items() if "aff" in b} - excluded


def collect_definitions():
    """(literal names, {prefix: names}, {suffix: names}, two-part prefixes)."""
    literal = set()
    prefixed = defaultdict(set)
    suffixed = defaultdict(set)
    twopart = defaultdict(set)

    for root in ("scripts", "triggers", "aliases"):
        base = os.path.join(SRC, root)
        if not os.path.isdir(base):
            continue
        for p in lua_files(base):
            s = read(p)
            literal |= set(re.findall(r"(?:svo\.)?valid\.([A-Za-z_]\w*)\s*=", s))
            literal |= set(re.findall(
                r"(?:svo\.)?valid\[['\"]([^'\"]+)['\"]\]\s*=", s))
            literal |= set(re.findall(
                r"function\s+(?:svo\.)?valid\.([A-Za-z_]\w*)", s))

    for parts in GENERATORS:
        src = read(os.path.join(SRC, "scripts", *parts))
        for m in re.finditer(r"valid\[\s*'([a-z_]+)'\s*\.\.\s*\w+\s*\]\s*=", src):
            prefixed[m.group(1)] |= loop_names(src, m.start())
        for m in re.finditer(r"valid\[\s*(\w+)\s*\.\.\s*'(\w+)'\s*\]\s*=", src):
            suffixed[m.group(2)] |= loop_names(src, m.start())
        for m in re.finditer(
                r"valid\[\s*'([a-z_]+)'\s*\.\.\s*\w+\s*\.\.\s*\w+\s*\]\s*=", src):
            twopart[m.group(1)] |= loop_names(src, m.start())

    prefixed["simple"] |= dict_simple_names()

    for pfx, names in HANDWRITTEN_DYNAMIC.items():
        prefixed[pfx] |= names

    return literal, dict(prefixed), dict(suffixed), dict(twopart)


def resolver(literal, prefixed, suffixed, twopart):
    def resolves(name):
        if name in literal:
            return True
        for pfx, names in prefixed.items():
            if name.startswith(pfx) and name[len(pfx):] in names:
                return True
        for suf, names in suffixed.items():
            if name.endswith(suf) and name[:-len(suf)] in names:
                return True
        # proper_<status><bodypart>: both halves come from the same loop table
        for pfx, names in twopart.items():
            if not name.startswith(pfx):
                continue
            rest = name[len(pfx):]
            for a in names:
                if rest.startswith(a) and rest[len(a):]:
                    return True
        return False
    return resolves


def collect_calls():
    calls = defaultdict(list)
    for root in ("triggers", "aliases"):
        base = os.path.join(SRC, root)
        if not os.path.isdir(base):
            continue
        for p in lua_files(base):
            rel = os.path.relpath(p, REPO).replace(os.sep, "/")
            for m in re.finditer(r"(?:svo\.)?\bvalid\.([A-Za-z_]\w*)\s*\(",
                                 read(p)):
                calls[m.group(1)].append(rel)
    return calls


def script_texts():
    """(where, script) for every trigger and alias script: the .lua files, and
    the scripts muddler keeps inline in the json, which collect_calls does not
    read. One name-taking call already lives inline."""
    for root in ("triggers", "aliases"):
        base = os.path.join(SRC, root)
        if not os.path.isdir(base):
            continue
        for d, _, fs in os.walk(base):
            for f in fs:
                p = os.path.join(d, f)
                rel = os.path.relpath(p, REPO).replace(os.sep, "/")
                if f.endswith(".lua"):
                    yield rel, read(p)
                elif f.endswith(".json"):
                    with io.open(p, encoding="utf-8") as fh:
                        stack = [json.load(fh)]
                    while stack:
                        x = stack.pop()
                        if isinstance(x, dict):
                            if isinstance(x.get("script"), str) and x["script"]:
                                yield "%s > %s" % (rel, x.get("name", "?")), x["script"]
                            stack.extend(x.values())
                        elif isinstance(x, list):
                            stack.extend(x)


def tree_special():
    """The strings svo.valid.tree_cured accepts besides an entry name, read
    from its own TREE_SPECIAL table rather than repeated here."""
    src = _read_script("svo (trigger functions)", "Main_trigger_functions.lua")
    m = re.search(r"local TREE_SPECIAL = \{(.*?)\n\}", src, re.S)
    return set(re.findall(r"\['([^']+)'\]\s*=\s*true", m.group(1))) if m else set()


def check_name_arguments():
    """(calls checked, problems) for the handlers in NAME_FAMILIES."""
    bals, _ = _dict_entries(_read_script(
        "svo (actions dictionary)", "Dictionary_of_actions_(affs-defs-misc).lua"))
    blocks = {n: set(b) for n, b in bals.items()}
    for n, b in RUNTIME_ENTRIES.items():
        blocks.setdefault(n, set()).update(b)
    # the def flag sits at the top of a balance's own body
    defences = {n for n, b in bals.items()
                if any(re.search(r"^\s*def\s*=\s*true\b", body, re.M)
                       for body in b.values())}
    special = tree_special()

    def why_not(fam, name):
        if fam == "tree_cured" and name in special:
            return None
        if fam == "diag" and name == "godfeelings":
            return None
        if name not in blocks:
            return "svof has no entry named %r" % name
        if fam == "diag" and "aff" not in blocks[name]:
            return "%r has no aff block, which diagnose_end indexes" % name
        if fam == "generic" and name in defences:
            return ("%r is a defence (a balance has def = true); defence lines "
                    "go to their own handler in svo.defs" % name)
        if fam in ("generic_cure", "generic_cured") and "gone" not in blocks[name]:
            return "%r has no gone block, which %s indexes" % (name, fam)
        return None

    call = re.compile(r"\bvalid\.(%s)\s*\(\s*([^)]*)\)" % "|".join(NAME_FAMILIES))
    checked, problems = 0, []
    for where, text in script_texts():
        for m in call.finditer(text):
            fam, args = m.group(1), m.group(2)
            lit = re.match(r"""\s*(['"])(.*?)\1""", args)
            if not lit:
                problems.append("%s calls svo.valid.%s(%s) with a name this check "
                                "cannot read; pass a literal" % (where, fam, args.strip()))
                continue
            checked += 1
            reason = why_not(fam, lit.group(2))
            if reason:
                problems.append("%s: svo.valid.%s(%r) - %s"
                                % (where, fam, lit.group(2), reason))
    if not special:
        problems.append("read no TREE_SPECIAL table from Main_trigger_functions.lua")
    return checked, problems


def load_known():
    if not os.path.exists(KNOWN):
        return set()
    with io.open(KNOWN, encoding="utf-8") as fh:
        return {(e["file"], e["name"]) for e in json.load(fh)["known"]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-known", action="store_true",
                    help="record the current unresolved calls and exit")
    a = ap.parse_args()

    literal, prefixed, suffixed, twopart = collect_definitions()
    resolves = resolver(literal, prefixed, suffixed, twopart)
    calls = collect_calls()

    generated = sum(len(v) for v in prefixed.values())

    problems = []
    if len(calls) < CALL_FLOOR:
        problems.append("found only %d distinct svo.valid calls, expected at "
                        "least %d - this check is reading less than it should"
                        % (len(calls), CALL_FLOOR))
    for pfx, floor in sorted(GENERATOR_FLOORS.items()):
        got = len(prefixed.get(pfx, ()))
        if got < floor:
            problems.append("the %r loop produced only %d names, expected at "
                            "least %d - it has stopped being readable, and "
                            "every call it should define now looks dead"
                            % (pfx, got, floor))

    named, name_problems = check_name_arguments()
    if named < NAME_CALL_FLOOR:
        problems.append("read only %d name arguments to %s, expected at least %d "
                        "- this check is reading less than it should"
                        % (named, "/".join(NAME_FAMILIES), NAME_CALL_FLOOR))

    unresolved = []
    for name in sorted(calls):
        if resolves(name):
            continue
        for f in sorted(set(calls[name])):
            unresolved.append({"file": f, "name": name})

    if a.write_known:
        if problems:
            print("refusing to record while the reading looks broken - "
                  "%s NOT written:" % KNOWN)
            for p in problems:
                print("  [FAIL] " + p)
            return 1
        payload = {
            "note": "svo.valid calls in src/triggers and src/aliases that "
                    "resolve to nothing. Every one is absent from the 2018 "
                    "module xmls too, so none is conversion damage. Recorded "
                    "so the count can only go down: a new one fails, and "
                    "fixing one of these fails until it is removed from here.",
            "known": sorted(unresolved, key=lambda e: (e["name"], e["file"])),
        }
        with io.open(KNOWN, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(payload, fh, indent=2)
            fh.write("\n")
        print("wrote %s: %d pre-existing unresolved call(s)"
              % (KNOWN, len(unresolved)))
        return 0

    known = load_known()
    new = [e for e in unresolved if (e["file"], e["name"]) not in known]
    fixed = known - {(e["file"], e["name"]) for e in unresolved}

    print("%d distinct svo.valid names called from src/triggers and "
          "src/aliases" % len(calls))
    print("  %d defined as literals, %d generated by %d loops"
          % (len(literal), generated, len(prefixed) + len(suffixed) + len(twopart)))
    print("%d name arguments to %s checked against svo.dict"
          % (named, "/".join(NAME_FAMILIES)))
    print()

    for e in new:
        print("[FAIL] svo.valid.%s() has no definition anywhere" % e["name"])
        print("           called from %s" % e["file"])
    for f, n in sorted(fixed):
        print("[FAIL] svo.valid.%s() is no longer an unresolved call, and %s "
              "still records it" % (n, os.path.basename(KNOWN)))
        print("           either a handler was written for it or its caller was "
              "removed - %s" % f)
        print("           drop that entry in the same commit that did it")
    for p in name_problems:
        print("[FAIL] " + p)
    for p in problems:
        print("[FAIL] " + p)

    bad = len(new) + len(fixed) + len(name_problems) + len(problems)
    if bad:
        print("\nsvo.valid is a plain table with no __index, so a name nothing "
              "defines\nraises into the error console and the trigger's line "
              "stops being acted on.")
        print("If a call is deliberately dead, record it with --write-known.")
        print("\nVALID CALL SITES FAILED - %d problem(s)" % bad)
        return 1

    print("every svo.valid call resolves (%d known pre-existing dead call(s) "
          "ignored)" % len(known))
    return 0


if __name__ == "__main__":
    sys.exit(main())
