name: 'Versioning and Tagging'
on:
  push:
    branches: [ gh-pages ]
    paths:
    - 'inclient/current_version.txt'

jobs:
  checkversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.SVOF_PAT }}
          ref: gh-pages
      - name: Get version
        id: getversion
        uses: michmich112/extract-version@main
        with:
          # specify here the path to your version file (e.g. package.json, pom.xml...)
          version-file: inclient/current_version.txt
          schema: major
          
      - name: Verify tag
        id: verifytag
        env:
          VersionToVerify: ${{ steps.getversion.outputs.version }}
        run: |
          echo "$VersionToVerify"
          if [ $(git tag -l $VersionToVerify) ]; then
            echo "{pushtag}={false}" >> $GITHUB_OUTPUT
          else
            echo "{pushtag}={true}" >> $GITHUB_OUTPUT
          fi
        
    outputs:
      version: ${{ steps.getversion.outputs.version }}
      canpushtag: ${{ steps.verifytag.outputs.pushtag }}
  
  createtag:
    needs: [checkversion]
    if: ${{ needs.checkversion.outputs.canpushtag == true }}
    runs-on: ubuntu-latest
    env:
      Version: ${{ needs.checkversion.outputs.version }}
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.SVOF_PAT }}
        ref: in-client-svof
        fetch-depth: 0
    
    - name: Push tag
      id: maketag
      env:
        GITHUB_TOKEN: ${{ secrets.SVOF_PAT }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git tag -a $Version -m "$Version"
        git push origin $Version
        
